# .github/workflows/python-tests.yml
name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"] # Run tests on Python versions 3.21

    steps:
      - uses: actions/checkout@v4 # Checks out the repository
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Install pytest and other dependencies,

      - name: Run pytest unit tests
        run: python -m pytest # Runs all tests 